# Use the official Python image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy only the updater-specific files and shared code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the script
CMD ["python", "-m", "scripts.update_api_data"]
