services:
  db:
    image: postgres:15
    container_name: postgres_db_price
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: price_service
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/price_service

volumes:
  postgres_data:
