"""remove price from hourly_bitcoin_prices

Revision ID: 2c03e8126fed
Revises: b5e8d7768640
Create Date: 2025-03-08 07:55:02.588195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c03e8126fed'
down_revision: Union[str, None] = 'b5e8d7768640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hourly_bitcoin_prices', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourly_bitcoin_prices', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
