"""Add unique constraint for user portfolios

Revision ID: 73a1d470ca01
Revises: 0e505d5d6039
Create Date: 2025-09-08 13:06:53.992995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a1d470ca01'
down_revision: Union[str, None] = '0e505d5d6039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_portfolio_name_uc', 'portfolios', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_portfolio_name_uc', 'portfolios', type_='unique')
    # ### end Alembic commands ###
